---
language: python
python: "2.7"

before_install:
#  - sudo apt-get install python-lxml
  # install current version of libxml
  - sudo apt-get install libxml2 libxml2-dev libxslt-dev python-dev
  - sudo CFLAGS="-O0"  pip install lxml --upgrade
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

script:
  - ansible --version

  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the miscellaneous tests.
  - "ansible-playbook -i tests/inventory tests/test.yml"
